
function initLevel() {
    level1 = new Level(
        [
            new Chicken(100, 275),
            new Chicken(250, 275),
            new Chick(450, 275),
            new Chicken(700, 275),
        ],
        [
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
        ],
        [
            new BackgroundObject('img/layers_bg/air.png', -719),
            new BackgroundObject('img/layers_bg/third_layer/2.png', -719),
            new BackgroundObject('img/layers_bg/second_layer/2.png', -719),
            new BackgroundObject('img/layers_bg/first_layer/2.png', -719),
            new BackgroundObject('img/layers_bg/air.png', 0),
            new BackgroundObject('img/layers_bg/third_layer/1.png', 0),
            new BackgroundObject('img/layers_bg/second_layer/1.png', 0),
            new BackgroundObject('img/layers_bg/first_layer/1.png', 0),
            new BackgroundObject('img/layers_bg/air.png', 719),
            new BackgroundObject('img/layers_bg/third_layer/2.png', 719),
            new BackgroundObject('img/layers_bg/second_layer/2.png', 719),
            new BackgroundObject('img/layers_bg/first_layer/2.png', 719),
            new BackgroundObject('img/layers_bg/air.png', 719 * 2),
            new BackgroundObject('img/layers_bg/third_layer/1.png', 719 * 2),
            new BackgroundObject('img/layers_bg/second_layer/1.png', 719 * 2),
            new BackgroundObject('img/layers_bg/first_layer/1.png', 719 * 2),
            new BackgroundObject('img/layers_bg/air.png', 719 * 3),
            new BackgroundObject('img/layers_bg/third_layer/2.png', 719 * 3),
            new BackgroundObject('img/layers_bg/second_layer/2.png', 719 * 3),
            new BackgroundObject('img/layers_bg/first_layer/2.png', 719 * 3),
            new BackgroundObject('img/layers_bg/air.png', 719 * 4),
            new BackgroundObject('img/layers_bg/third_layer/1.png', 719 * 4),
            new BackgroundObject('img/layers_bg/second_layer/1.png', 719 * 4),
            new BackgroundObject('img/layers_bg/first_layer/1.png', 719 * 4),
            new BackgroundObject('img/layers_bg/air.png', 719 * 5),
            new BackgroundObject('img/layers_bg/third_layer/2.png', 719 * 5),
            new BackgroundObject('img/layers_bg/second_layer/2.png', 719 * 5),
            new BackgroundObject('img/layers_bg/first_layer/2.png', 719 * 5),
            new BackgroundObject('img/layers_bg/air.png', 719 * 6),
            new BackgroundObject('img/layers_bg/third_layer/1.png', 719 * 6),
            new BackgroundObject('img/layers_bg/second_layer/1.png', 719 * 6),
            new BackgroundObject('img/layers_bg/first_layer/1.png', 719 * 6),
            new BackgroundObject('img/layers_bg/air.png', 719 * 7),
            new BackgroundObject('img/layers_bg/third_layer/2.png', 719 * 7),
            new BackgroundObject('img/layers_bg/second_layer/2.png', 719 * 7),
            new BackgroundObject('img/layers_bg/first_layer/2.png', 719 * 7),
        ],
        [
            new Coin(0, 200),
            new Coin(100, 200),
            new Coin(200, 150),
            new Coin(800, 100),
            new Coin(850, -50),
            new Coin(950, 0),
            new Coin(1100, 100),
            new Coin(1350, 200),
            new Coin(1200, 150),
            new Coin(1900, -5),
            new Coin(2000, 100),
            new Coin(2250, -50),
            new Coin(2200, 150),
            new Coin(2500, 50),
            new Coin(3000, -50),
            new Coin(3150, 75),
            new Coin(3450, 100),
            new Coin(3550, -50),
            new Coin(3600, 150),
            new Coin(3900, 50),
        ],
        [
            new Bottles(0, 375),
            new Bottles(100, 375),
        ],
        [new Endboss()]
    );
}

